### PR TITLE
Refact tests

### PR DESCRIPTION
**Pull request by francoismassart**
- Using `const` instead of `let`
- Better variable names
- Using `triggerEvent()` method when possible

MINOR: using keydown instead of keyup.prevent for TimePicker (reducing jumping cursor while using keyboard)

@wxsms

### CODE REVIEW

**Comment by wxsms** [comment]
This is amazing...

**Comment by wxsms** [comment]
Wow, there're lots of work... Thanks!

**Comment by francoismassart** [comment]
Not perfect, but some improvements 👍

**Comment by wxsms** [comment]
d2494709be7da04388a27e29a25b69c74ef84ea7 Found the reason of coverage drop.

**Pull request merged**
