### PR TITLE
Enhance the `<input>` for `TimePicker`

### LINKED ISSUE #95: Enhance the `<input>` of the `TimePicker`
### Version & browser
`0.2.13` on most browsers

### Which component
`TimePicker`

### Steps to reproduce the problem
Editing the hours and minutes shows the default virtual keyboard on mobile devices...

### Expected behavior
It would be nicer to benefit (when possible) from the new input types provided by HTML5.

### Actual behavior
Currently the `<input>` used for HH and MM are not using the type attribute which fallbacks to the default aka `type="text"`

### Proposed improvements coming in a PR
- Use the `type="number"` which will cause the virtual keyboard to show up the number keys on Android mobile browsers. Browsers which do not support `number` input type will fallback to the default type which is `text`
- Define the `min` and `max` values using the HTML5 attributes
- Define the `pattern` attribute with the correct regular expression `\d{1,2}` the pattern doesn't seem to do much on Android browsers but is useful for iOS browsers
- Add `<style>` hiding the native step up/down buttons (desktop browsers)
- Ensuring we keep a "0" padding for values between 0 and 9

Please let me know if you have comments.

### PR DESCRIPTION
**Pull request by francoismassart**
Fixes #95 

Changes proposed in this pull request:

- `type="number"`
- `min`, `max`, `pattern`, `maxlength` attributes
- `<style>` hiding the native stepper buttons on desktop browsers

@wxsms

### CODE REVIEW

**Comment by francoismassart** [comment]
Safari & Chrome keep the nice "0" padding for value between 0 and 9 while the "0" is omitted in Firefox... I'll take a look at it.

**Comment by francoismassart** [comment]
If we want to keep the leading "0", we should use the `type="phone"`... We would loose the usage of `min` and `max` attributes. It could do the trick... Using `type="phone"` we can erase the `<style>`.

Pros for `type="number"` | Cons for `type="number"` 
----------------- | ---------
Type `number` is "closer" to the `type="time"` | Leading zero won't works on Firefox
`min` and `max` attributes can be used (minor) | We need for additional `<style>`
Virtual keyboard will show number keys 👍  | 

Pros for `type="phone"` | Cons for `type="phone"` 
----------------- | ---------
Leading zero works on Firefox | Type `number` makes a little more sens
No need for additional `<style>` | `min` and `max` attributes won't be used (minor)
Virtual keyboard will show number keys 👍  | 

**NOTE: `type="time"` would be perfect but at this time almost each browser render it differently, and I'm not even talking about how/when their change event is emited so it's getting quite nasty.**

**Comment by wxsms** [comment]
Hi @francoismassart 

Seems `type=phone` is better.

1. Forget about the min / max, they already handle by vue value validation.
2. `<style>` inside component is not well supported by now.
   * If exact them to `css` file, then user will need to import one more thing to use this lib.
   * If keep them in `js` file, then it will break SSR process (don't know why, maybe a Vue issue).

I've try `type=number` at the beginning of making timepicker, and finally I give it up.

**Comment by francoismassart** [comment]
Let me adapt this using `type="phone"`, then we can test it out and finally merge or discard the PR. I'll commit in few minutes.

**Comment by francoismassart** [comment]
Sadly, after testing on Android, it seems to keep showing up the full keyboard and not the number pad 👎  (Yet, it is the same behaviour than before my changes)

**Comment by wxsms** [comment]
Seems `phone` is not a standard input type, maybe you should try `tel`

**Comment by francoismassart** [comment]
Indeed, it should be `tel`, not `phone`. I also get issues in iOS while trying to edit the field itself...
e.g. trying to type "10"

So wait up until you bundle it into a release!
I'll keep working on this and let you know.

**Pull request merged**
