### PR TITLE
Model Backdrop was "click", now "mousedown"

### PR DESCRIPTION
**Pull request by danielhuggins**
As mentioned in #285 when someone starts a click event inside the modal content area, and then releases it outside, in the backdrop, the modal hides. This is a frustrating issue when selecting text in the modal, as I often do. This only happens in chrome and is also an issue in bootstrap jquery itself. 

This is the simplest possible fix - replacing @click.self with @mousedown.self. This avoids the weird chrome behaviour.

This does change the timing of the dismissal. Are any users relying on their own @mouseup or @mousedown events firing before the backdrop event? I think that none are.

### CODE REVIEW

**Comment by wxsms** [comment]
Could you pls try fix the unit test errors? thanks.

**Comment by danielhuggins** [comment]
Thanks, didn't see those until now. Will do when i get some free time later this week.

**Comment by danielhuggins** [comment]
Hi wxsms, could you please tell me where to go next with this? I've fixed the unit test errors and they are all passing. I'm sure this is the right way to go with the modals - anything else would introduce a great deal of complexity.

**Comment by danielhuggins** [comment]
Hi @wxsms , could you please tell me where to go next with this? I've fixed the unit test errors and they are all passing. I'm sure this is the right way to go with the modals - anything else would introduce a great deal of complexity.

**Comment by wxsms** [comment]
Merged, thanks.

**Pull request merged**
