### PR TITLE
Add support for long presses on keys and buttons

### PR DESCRIPTION
**Pull request by francoismassart**
For both desktop and mobile device’s touchscreens

Changing the value is way faster and easier using few long touches instead of:

Using input

    Tap the field (focus)
    Have the Virtual Keyboard slideup
    Type the digits
    Leave the field (blur)

Using buttons

    Tap
    Tap
    Tap ... multiple times (frustrating on touchscreens)
    Also tapping twice could be interpreted by iOS as "Zoom in" which is not what the user wants to do

**Long presses on touch screen is easy and fast...**

@wxsms

### CODE REVIEW

**Comment by francoismassart** [comment]
I am writing more test in order to increase the coverage...

**Comment by wxsms** [comment]
Hi @francoismassart 

just read your code, looks workable. but I think `mouseleave` / `mouseout` should also bind to the stop event.

**Comment by wxsms** [comment]
It's good to have your new functions covered by test. You can check the coverage at `test/unit/coverage/lcov-report/index.html`.

Thanks!

**Comment by francoismassart** [comment]
I'll do this 👍

**Comment by francoismassart** [comment]
@wxsms I'll let you know when I'm done and ready for your code review!

**Comment by francoismassart** [comment]
Hello @wxsms , I added support for `mouseleave` and I did implement additional tests.

Let me know what you think!

**Comment by wxsms** [comment]
Thanks, let me check this out.

**Comment by wxsms** [comment]
Hi.

Just test your implementation. **A significant problem is, 'fast clicking' is not working any more**, every btn in timepicker is sharing the same cold-down time, it feels kind of strange.

I still don't like the idea of 'long press' here, **it is not in any part of the original bootstrap**, and it **makes a simple component becomes too complicated**, hard to test across browsers / devices.

Therefore, this one is reverting. **Next time when you come up with some ideas, pls make sure to open an issue and WAIT for a positive response from collaborator BEFORE you start you work.**

After all, thanks very much for your contributions to this lib.

**Comment by francoismassart** [comment]
The idea was to get closer to the native behaviour of HTML5 `<input type="number">`, and it is especially useful on mobile devices but no problem if you don't want it.

**Pull request merged**
